### ISSUE TITLE
Undefined symbol __rbitll on Linux ARM with 3.2.0-rc1

### ISSUE THREAD

**Issue by oscarbenjamin** [flintlib/flint#2243]
I was testing 3.2.0-rc1 and found that it failed to build on Linux ARM in CI:
https://github.com/flintlib/python-flint/pull/264

The build fails with:
```
2025-03-03T12:41:33.7528498Z   CC  ulong_extras/primitive_root_prime.c
2025-03-03T12:41:33.7529610Z /project/.local/src/flint-3.2.0-rc1/src/ulong_extras/revbin.c: In function ‘n_revbin’:
2025-03-03T12:41:33.7538559Z /project/.local/src/flint-3.2.0-rc1/src/ulong_extras/revbin.c:22:9: error: implicit declaration of function ‘__rbitll’ [-Werror=implicit-function-declaration]
2025-03-03T12:41:33.7539839Z    22 |     n = __rbitll(n);
2025-03-03T12:41:33.7540559Z       |         ^~~~~~~~
2025-03-03T12:41:33.7618319Z /project/.local/src/flint-3.2.0-rc1/src/ulong_extras/revbin.c: At top level:
2025-03-03T12:41:33.7625654Z cc1: note: unrecognized command-line option ‘-Wno-stringop-overread’ may have been intended to silence earlier diagnostics
2025-03-03T12:41:33.7638086Z cc1: some warnings being treated as errors
2025-03-03T12:41:33.7729840Z make: *** [build/ulong_extras/revbin.lo] Error 1
```
FLINT's main branch builds fine though so I guess the problem is already fixed (although I'm not sure by what). 

I just want to check that the fix will make it into 3.2.0 final...

Also GitHub Actions recently added Linux ARM runners which is what I am using to test this. Are those tested in FLINT's CI?

To use the ARM runners you can just set:
```
runs-on: ubuntu-24.04-arm
```

**Comment by albinahlback** [comment]
That's weird.  It should be defined according to ARM C language extension.  I'll look into it before we release 3.2.0.

**Comment by albinahlback** [comment]
I've implemented the ARM runner, and will now try to check what goes wrong for 3.2.0-rc1.

**Comment by agriyakhetarpal** [comment]
Thanks, @albinahlback – it's coming from the fact that the ARM build here is using the `ubuntu-24.04-arm` runner with GCC 13.3.0, but https://github.com/flintlib/python-flint/actions/runs/13631086251/job/38098838101?pr=264 builds for the `manylinux2014` platform tag using its Docker images, which conforms to an older toolchain[^1] (GCC 10.2.1).

@oscarbenjamin, I think this might be the right time to bump to `manylinux_2_28` as it brings GCC 14. I have to mention that it was earlier going to be the default in `cibuildwheel` in June 2025 (with `cibuildwheel` v3, most likely, see https://github.com/pypa/cibuildwheel/issues/1772), but the Amazon Linux 2 team (which ships glibc 2.26) postponed their EoL date to June 2026, so it might be delayed.

[`python-flint` requires Python >=3.11](https://github.com/flintlib/python-flint/blob/deed5b1f1ccbf7d4bdb8b3940459e6447d4010b9/pyproject.toml#L6) anyway, which is fine for glibc 2.28. For greater compatibility across platforms, we can go ahead with `manylinux_2_28` just for AArch64 and keep `manylinux2014` for the rest, using https://cibuildwheel.pypa.io/en/stable/options/#linux-image.

[^1]: Based on information provided via https://manylinuxinspector.joerick.me/#/manylinux2014/2025.02.28-1.

**Comment by oscarbenjamin** [comment]
> I think this might be the right time to bump to `manylinux_2_28` as it brings GCC 14

Ah, thanks.

**Comment by agriyakhetarpal** [comment]
> I'll try with `--host` instead since I guess that is the preferred way as of FLINT 3.2.

This would be useful to try, too, there is no use in breaking compatibility if we can still support glibc 2.17.

**Comment by oscarbenjamin** [comment]
I tried `--host` and it made no difference but bumping the manylinux version to 2.17 to use GCC 14 makes a difference. Now it fails with a different error:
```
2025-03-05T14:09:29.7038332Z   CC  mpn_extras/mulhigh.c
2025-03-05T14:09:29.7537454Z In file included from /project/.local/src/flint-3.2.0-rc1/src/fft_small.h:16,
2025-03-05T14:09:29.7538610Z                  from /project/.local/src/flint-3.2.0-rc1/src/mpn_extras/mul.c:41:
2025-03-05T14:09:29.7540350Z /project/.local/src/flint-3.2.0-rc1/src/machine_vectors.h: In function ‘vec2n_store_unaligned’:
2025-03-05T14:09:29.7558778Z /project/.local/src/flint-3.2.0-rc1/src/machine_vectors.h:1472:14: error: passing argument 1 of ‘vst1q_u64’ from incompatible pointer type [-Wincompatible-pointer-types]
2025-03-05T14:09:29.7560479Z  1472 |    vst1q_u64((unsigned long long *) z, a);
2025-03-05T14:09:29.7561183Z       |              ^~~~~~~~~~~~~~~~~~~~~~~~
2025-03-05T14:09:29.7562007Z       |              |
2025-03-05T14:09:29.7562355Z       |              long long unsigned int *
2025-03-05T14:09:29.7587981Z In file included from /project/.local/src/flint-3.2.0-rc1/src/machine_vectors.h:24:
2025-03-05T14:09:29.7590352Z /opt/rh/gcc-toolset-14/root/usr/lib/gcc/aarch64-redhat-linux/14/include/arm_neon.h:22181:22: note: expected ‘uint64_t *’ {aka ‘long unsigned int *’} but argument is of type ‘long long unsigned int *’
2025-03-05T14:09:29.7591864Z 22181 | vst1q_u64 (uint64_t *__a, uint64x2_t __b)
2025-03-05T14:09:29.7592655Z       |            ~~~~~~~~~~^~~
2025-03-05T14:09:29.7603994Z /project/.local/src/flint-3.2.0-rc1/src/machine_vectors.h: In function ‘vec2n_load_unaligned’:
2025-03-05T14:09:29.7605791Z /project/.local/src/flint-3.2.0-rc1/src/machine_vectors.h:1485:22: error: passing argument 1 of ‘vld1q_u64’ from incompatible pointer type [-Wincompatible-pointer-types]
2025-03-05T14:09:29.7607138Z  1485 |     return vld1q_u64((const unsigned long long *) a);
2025-03-05T14:09:29.7608470Z       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2025-03-05T14:09:29.7608849Z       |                      |
2025-03-05T14:09:29.7609229Z       |                      const long long unsigned int *
2025-03-05T14:09:29.7618832Z /opt/rh/gcc-toolset-14/root/usr/lib/gcc/aarch64-redhat-linux/14/include/arm_neon.h:12830:28: note: expected ‘const uint64_t *’ {aka ‘const long unsigned int *’} but argument is of type ‘const long long unsigned int *’
2025-03-05T14:09:29.7620130Z 12830 | vld1q_u64 (const uint64_t *__a)
2025-03-05T14:09:29.7620471Z       |            ~~~~~~~~~~~~~~~~^~~
2025-03-05T14:09:29.7771561Z make: *** [Makefile:637: build/mpn_extras/mul.lo] Error 1
2025-03-05T14:09:29.7772448Z make: *** Waiting for unfinished jobs....
```
This is tested in:
https://github.com/flintlib/python-flint/pull/264

**Comment by albinahlback** [comment]
I was wrong.  The `rbit` instruction is not necessarily available on all CPUs.  I'll have to fix this.

**Comment by albinahlback** [comment]
@oscarbenjamin can you check if https://github.com/flintlib/flint/pull/2245 works for your compiler?

**Comment by albinahlback** [comment]
@oscarbenjamin #2246 should fix the next error.

**Comment by oscarbenjamin** [comment]
> can you check if [#2245](https://github.com/flintlib/flint/pull/2245) works for the compiler that previously failed?

It still fails with `error: implicit declaration of function ‘__rbitll’` when using GCC 10.

> [#2246](https://github.com/flintlib/flint/pull/2246) should fix the next error.

With gh-2446 and GCC 14 the FLINT build completes.

**Comment by albinahlback** [comment]
> > can you check if [#2245](https://github.com/flintlib/flint/pull/2245) works for the compiler that previously failed?
> 
> It still fails with `error: implicit declaration of function ‘__rbitll’` when using GCC 10.

Okay, then it was a bug in GCC (they refer to the ACLE which states that the implemented check should work).

> > [#2246](https://github.com/flintlib/flint/pull/2246) should fix the next error.
> 
> With [gh-2246](https://github.com/flintlib/flint/pull/2246) and GCC 14 the FLINT build completes.

Perfect, I'll incorporate this soon.

**Comment by albinahlback** [comment]
This should be fixed as of #2245.  However, the bug in GCC 10 still remains, but I will not do a workaround for this.

**Comment by oscarbenjamin** [comment]
I tested this with rc2 in https://github.com/flintlib/python-flint/pull/266 and I confirm that it seems to be fixed.
