### ISSUE TITLE
Configure fails for emscripten/wasm build with 3.2.0-rc1

### ISSUE THREAD

**Issue by oscarbenjamin** [flintlib/flint#2247]
Building FLINT for wasm fails with 3.2.0-rc1 although it previously worked for 3.1. The build fails to configure with:
```
checking if system can use FLINT's fft_small module... no
configure: WARNING: Currently no assembly available for 32-bit systems. Disabling assembly...
checking how to switch to text section... .text
configure: error: Cannot determine label suffix
emconfigure: error: './configure --disable-dependency-tracking --disable-shared --prefix=/home/runner/work/python-flint/python-flint/wasm-library-dir --with-gmp=/home/runner/work/python-flint/python-flint/wasm-library-dir --with-mpfr=/home/runner/work/python-flint/python-flint/wasm-library-dir' failed (returned 1)
checking for assembler label suffix... 
```
The configure script tries to determine the label suffix for assembly code but the assembly code cannot be used on wasm as it is only for x86_64 and arm64. I guess ideally configure would fall back on not using assembly here rather than erroring out.

To reproduce this first install emscripten (e.g.. `sudo apt-get install emscripten`) and then build GMP, MPFR and FLINT but using `emconfigure` and `emmake` instead of `./configure` and `make`. I haven't actually tested these steps myself but you can see the commands in the CI job at https://github.com/flintlib/python-flint/pull/262/files.

This comes from https://github.com/flintlib/python-flint/pull/262#issuecomment-2702446618 which is trying to build python-flint with the latest version of FLINT to run in the browser.

**Comment by albinahlback** [comment]
This should be fixed as of #2248.  Please make sure that WASM builds correctly on `main`, and I will cherry-pick everything in the last days into 3.2.0.

**Comment by oscarbenjamin** [comment]
Thanks. We'll check this.

**Comment by agriyakhetarpal** [comment]
Looks like the error persists: https://github.com/agriyakhetarpal/python-flint/actions/runs/13710749723/job/38346563289

**Comment by albinahlback** [comment]
Then I don't understand it.  Is it just the compiler that is incapable of using labels?  Or is the host platform not really Zen 3?

**Comment by agriyakhetarpal** [comment]
🤔 Emscripten should be capable of labels. The host isn't Zen 3, though. WebAssembly is architecture-agnostic, but its runtimes differ based on browser and OS/platform combos. I could try to bisect between 3.1.3 and 3.2.0-rc1 and find where the failure started.

**Comment by albinahlback** [comment]
The problem isn't with FLINT.  You have to specify the correct CPU.  If you (indirectly) push Zen 3, it will try to spit out code for Zen 3.  Perhaps `host_cpu` should be `wasm64`?

**Comment by agriyakhetarpal** [comment]
I don't think Emscripten supports specifying CPUs as it doesn't optimise for CPU instructions and WASM runtimes often use JIT. Is there a baseline option that can be chosen? We've set the host to `wasm32-unknown-emscripten` in the time being. `wasm64` (Memory64) isn't supported yet, as it hasn't been standardised across browsers and is available only behind the `--experimental-wasm-memory64` flag. For WASM/Pyodide, we'll be needing `wasm32`, at least for now.

**Comment by oscarbenjamin** [comment]
> Looks like the error persists: https://github.com/agriyakhetarpal/python-flint/actions/runs/13710749723/job/38346563289

There was a problem with the CI config meaning that the `--host` argument was not being passed to `./configure`:
https://github.com/flintlib/python-flint/pull/262/commits/70bf4b694296176a8f196a96cf383b2f842f0cde

After fixing that the error does not persist so it looks like this is fixed.

**Comment by oscarbenjamin** [comment]
> This should be fixed as of [#2248](https://github.com/flintlib/flint/pull/2248).

This fix was still necessary. It would be good if that can go into 3.2.0.

Thanks Albin!

**Comment by albinahlback** [comment]
Will keep it open until the full release.

**Comment by albinahlback** [comment]
Should be fixed as of [v3.2.0-rc2](https://github.com/flintlib/flint/releases/tag/v3.2.0-rc2).  Please reopen if the issue persists.  We will release v3.2.0 tomorrow probably.

**Comment by oscarbenjamin** [comment]
Testing rc2 in https://github.com/flintlib/python-flint/pull/266 to see that https://github.com/flintlib/flint/issues/2243 is fixed.

**Comment by oscarbenjamin** [comment]
This issue seems to be fixed in rc2 according to my testing in https://github.com/flintlib/python-flint/pull/262.
