### ISSUE TITLE
Installed headers refer to non-existent headers

### ISSUE THREAD

**Issue by yurivict** [flintlib/flint#462]
This header include/flint/fmpzxx.h has:
```
#include "flintxx/evaluation_tools.h"
#include "flintxx/expression.h"
#include "flintxx/expression_traits.h"
#include "flintxx/flint_classes.h"
#include "flintxx/frandxx.h"
#include "flintxx/ltuple.h"
#include "flintxx/stdmath.h"
```
which aren't installed.

**Comment by wbhart** [comment]
Later this morning I'll add a "make exist" target to the Makefile if Lirpa
Sloof doesn't beat me to it.

**Comment by wbhart** [comment]
These seem to exist when installed from Flint/trunk. So I believe this has been fixed.

**Comment by real-or-random** [comment]
I believe this is still an issue with the cmake build. 

On my Arch Linux, there's no `flintxx` subdir in `/usr/include/flint` (no subdirs at all) and they use cmake:
https://github.com/archlinux/svntogit-community/blob/f462aa603168e45c7631a45ef39b19a5589bdc4e/trunk/PKGBUILD 

In fact which build would you recommend? Is the configure/make build better maintained than the cmake build?

**Comment by wbhart** [comment]
Both builds should work. Let's see if the CMake people can look at this if I reopen the ticket.
